//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Information_Security_Conference.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activyti_and_Zhuri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activyti_and_Zhuri()
        {
            this.Event_actions = new HashSet<Event_actions>();
        }
    
        public int IDActivyti { get; set; }
        public int Day { get; set; }
        public System.TimeSpan Time { get; set; }
        public int IDModerator { get; set; }
        public int ID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Moderatory Moderatory { get; set; }
        public virtual List_activyti_and_Zhuri List_activyti_and_Zhuri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_actions> Event_actions { get; set; }
    }
}
