//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Information_Security_Conference.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_actions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event_actions()
        {
            this.Activyti_and_Zhuri = new HashSet<Activyti_and_Zhuri>();
        }
    
        public int ID { get; set; }
        public int IDEvent { get; set; }
        public int IDAction { get; set; }
        public System.DateTime Date_start { get; set; }
        public int Days { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activyti_and_Zhuri> Activyti_and_Zhuri { get; set; }
    }
}
