//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Information_Security_Conference.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_activyti_and_Zhuri
    {
        public int ID_activyti { get; set; }
        public Nullable<int> ID_Zhuri { get; set; }
    
        public virtual Activyti_and_Zhuri Activyti_and_Zhuri { get; set; }
        public virtual Zhuri Zhuri { get; set; }
    }
}
