//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Information_Security_Conference.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zhuri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zhuri()
        {
            this.List_activyti_and_Zhuri = new HashSet<List_activyti_and_Zhuri>();
        }
    
        public int IDZhuri { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int IDGender { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthdate { get; set; }
        public int IDCountry { get; set; }
        public string Telephone { get; set; }
        public int IDDirection { get; set; }
        public int UniqueID { get; set; }
        public string Photo { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List_activyti_and_Zhuri> List_activyti_and_Zhuri { get; set; }
    }
}
